"""
Indonesia Location Database
Daftar lengkap 38 provinsi dan kota/kabupaten di Indonesia untuk fuzzy matching
"""

# 38 Provinsi Indonesia (updated 2024)
PROVINSI_INDONESIA = [
    "ACEH",
    "SUMATERA UTARA",
    "SUMATERA BARAT",
    "RIAU",
    "JAMBI",
    "SUMATERA SELATAN",
    "BENGKULU",
    "LAMPUNG",
    "KEPULAUAN BANGKA BELITUNG",
    "KEPULAUAN RIAU",
    "DKI JAKARTA",
    "JAWA BARAT",
    "JAWA TENGAH",
    "DI YOGYAKARTA",
    "JAWA TIMUR",
    "BANTEN",
    "BALI",
    "NUSA TENGGARA BARAT",
    "NUSA TENGGARA TIMUR",
    "KALIMANTAN BARAT",
    "KALIMANTAN TENGAH",
    "KALIMANTAN SELATAN",
    "KALIMANTAN TIMUR",
    "KALIMANTAN UTARA",
    "SULAWESI UTARA",
    "SULAWESI TENGAH",
    "SULAWESI SELATAN",
    "SULAWESI TENGGARA",
    "GORONTALO",
    "SULAWESI BARAT",
    "MALUKU",
    "MALUKU UTARA",
    "PAPUA",
    "PAPUA BARAT",
    "PAPUA SELATAN",
    "PAPUA TENGAH",
    "PAPUA PEGUNUNGAN",
    "PAPUA BARAT DAYA",
]

# Kota dan Kabupaten di Indonesia (sample yang umum, bisa dilengkapi)
KOTA_KABUPATEN_INDONESIA = [
    # Aceh
    "BANDA ACEH",
    "SABANG",
    "LHOKSEUMAWE",
    "LANGSA",
    "SUBULUSSALAM",
    "ACEH BESAR",
    "ACEH BARAT",
    "ACEH SELATAN",
    "ACEH TIMUR",
    "ACEH UTARA",
    # Sumatera Utara
    "MEDAN",
    "BINJAI",
    "TEBING TINGGI",
    "PEMATANG SIANTAR",
    "TANJUNG BALAI",
    "PADANG SIDEMPUAN",
    "GUNUNGSITOLI",
    "DELI SERDANG",
    "LANGKAT",
    "SERDANG BEDAGAI",
    "KARO",
    "ASAHAN",
    "LABUHANBATU",
    "TAPANULI UTARA",
    "TAPANULI TENGAH",
    "TAPANULI SELATAN",
    # Sumatera Barat
    "PADANG",
    "BUKITTINGGI",
    "PADANG PANJANG",
    "PAYAKUMBUH",
    "SOLOK",
    "SAWAHLUNTO",
    "PARIAMAN",
    "AGAM",
    "LIMA PULUH KOTA",
    "PASAMAN",
    "SIJUNJUNG",
    # Riau
    "PEKANBARU",
    "DUMAI",
    "BENGKALIS",
    "INDRAGIRI HILIR",
    "INDRAGIRI HULU",
    "KAMPAR",
    "PELALAWAN",
    "ROKAN HILIR",
    "ROKAN HULU",
    "SIAK",
    # Kepulauan Riau
    "BATAM",
    "TANJUNG PINANG",
    "BINTAN",
    "KARIMUN",
    "LINGGA",
    "NATUNA",
    # Jambi
    "JAMBI",
    "SUNGAI PENUH",
    "BATANG HARI",
    "BUNGO",
    "KERINCI",
    "MERANGIN",
    "MUARO JAMBI",
    "SAROLANGUN",
    "TANJUNG JABUNG BARAT",
    "TANJUNG JABUNG TIMUR",
    "TEBO",
    # Sumatera Selatan
    "PALEMBANG",
    "PRABUMULIH",
    "LUBUKLINGGAU",
    "PAGAR ALAM",
    "BANYUASIN",
    "EMPAT LAWANG",
    "LAHAT",
    "MUARA ENIM",
    "MUSI BANYUASIN",
    "MUSI RAWAS",
    "OGAN ILIR",
    "OGAN KOMERING ILIR",
    "OGAN KOMERING ULU",
    # Bengkulu
    "BENGKULU",
    "BENGKULU SELATAN",
    "BENGKULU TENGAH",
    "BENGKULU UTARA",
    "KAUR",
    "KEPAHIANG",
    "LEBONG",
    "MUKOMUKO",
    "REJANG LEBONG",
    "SELUMA",
    # Lampung
    "BANDAR LAMPUNG",
    "METRO",
    "LAMPUNG BARAT",
    "LAMPUNG SELATAN",
    "LAMPUNG TENGAH",
    "LAMPUNG TIMUR",
    "LAMPUNG UTARA",
    "MESUJI",
    "PESAWARAN",
    "PESISIR BARAT",
    "PRINGSEWU",
    "TANGGAMUS",
    "TULANG BAWANG",
    "WAY KANAN",
    # Bangka Belitung
    "PANGKAL PINANG",
    "BANGKA",
    "BANGKA BARAT",
    "BANGKA SELATAN",
    "BANGKA TENGAH",
    "BELITUNG",
    "BELITUNG TIMUR",
    # DKI Jakarta
    "JAKARTA PUSAT",
    "JAKARTA UTARA",
    "JAKARTA BARAT",
    "JAKARTA SELATAN",
    "JAKARTA TIMUR",
    "KEPULAUAN SERIBU",
    # Jawa Barat
    "BANDUNG",
    "BEKASI",
    "BOGOR",
    "CIMAHI",
    "CIREBON",
    "DEPOK",
    "SUKABUMI",
    "TASIKMALAYA",
    "BANJAR",
    "BANDUNG BARAT",
    "CIAMIS",
    "CIANJUR",
    "GARUT",
    "INDRAMAYU",
    "KARAWANG",
    "KUNINGAN",
    "MAJALENGKA",
    "PANGANDARAN",
    "PURWAKARTA",
    "SUBANG",
    "SUMEDANG",
    # Jawa Tengah
    "SEMARANG",
    "SURAKARTA",
    "MAGELANG",
    "SALATIGA",
    "PEKALONGAN",
    "TEGAL",
    "BANJARNEGARA",
    "BANYUMAS",
    "BATANG",
    "BLORA",
    "BOYOLALI",
    "BREBES",
    "CILACAP",
    "DEMAK",
    "GROBOGAN",
    "JEPARA",
    "KARANGANYAR",
    "KEBUMEN",
    "KENDAL",
    "KLATEN",
    "KUDUS",
    "PATI",
    "PEMALANG",
    "PURBALINGGA",
    "PURWOREJO",
    "REMBANG",
    "SRAGEN",
    "SUKOHARJO",
    "TEMANGGUNG",
    "WONOGIRI",
    "WONOSOBO",
    # DI Yogyakarta
    "YOGYAKARTA",
    "BANTUL",
    "GUNUNGKIDUL",
    "KULON PROGO",
    "SLEMAN",
    # Jawa Timur
    "SURABAYA",
    "MALANG",
    "BATU",
    "BLITAR",
    "KEDIRI",
    "MADIUN",
    "MOJOKERTO",
    "PASURUAN",
    "PROBOLINGGO",
    "BANYUWANGI",
    "BONDOWOSO",
    "BOJONEGORO",
    "GRESIK",
    "JEMBER",
    "JOMBANG",
    "LAMONGAN",
    "LUMAJANG",
    "MAGETAN",
    "NGANJUK",
    "NGAWI",
    "PACITAN",
    "PAMEKASAN",
    "PONOROGO",
    "SIDOARJO",
    "SITUBONDO",
    "SUMENEP",
    "TRENGGALEK",
    "TUBAN",
    "TULUNGAGUNG",
    # Banten
    "TANGERANG",
    "TANGERANG SELATAN",
    "SERANG",
    "CILEGON",
    "LEBAK",
    "PANDEGLANG",
    # Bali
    "DENPASAR",
    "BADUNG",
    "BANGLI",
    "BULELENG",
    "GIANYAR",
    "JEMBRANA",
    "KARANGASEM",
    "KLUNGKUNG",
    "TABANAN",
    # Nusa Tenggara Barat
    "MATARAM",
    "BIMA",
    "BIMA",
    "DOMPU",
    "LOMBOK BARAT",
    "LOMBOK TENGAH",
    "LOMBOK TIMUR",
    "LOMBOK UTARA",
    "SUMBAWA",
    "SUMBAWA BARAT",
    # Nusa Tenggara Timur
    "KUPANG",
    "ALOR",
    "BELU",
    "ENDE",
    "FLORES TIMUR",
    "KUPANG",
    "LEMBATA",
    "MANGGARAI",
    "MANGGARAI BARAT",
    "MANGGARAI TIMUR",
    "NAGEKEO",
    "NGADA",
    "ROTE NDAO",
    "SABU RAIJUA",
    "SIKKA",
    "SUMBA BARAT",
    "SUMBA BARAT DAYA",
    "SUMBA TENGAH",
    "SUMBA TIMUR",
    "TIMOR TENGAH SELATAN",
    "TIMOR TENGAH UTARA",
    # Kalimantan Barat
    "PONTIANAK",
    "SINGKAWANG",
    "BENGKAYANG",
    "KAPUAS HULU",
    "KAYONG UTARA",
    "KETAPANG",
    "KUBU RAYA",
    "LANDAK",
    "MELAWI",
    "MEMPAWAH",
    "SAMBAS",
    "SANGGAU",
    "SEKADAU",
    "SINTANG",
    # Kalimantan Tengah
    "PALANGKARAYA",
    "BARITO SELATAN",
    "BARITO TIMUR",
    "BARITO UTARA",
    "GUNUNG MAS",
    "KAPUAS",
    "KATINGAN",
    "KOTAWARINGIN BARAT",
    "KOTAWARINGIN TIMUR",
    "LAMANDAU",
    "MURUNG RAYA",
    "PULANG PISAU",
    "SUKAMARA",
    "SERUYAN",
    # Kalimantan Selatan
    "BANJARMASIN",
    "BANJARBARU",
    "BALANGAN",
    "BANJAR",
    "BARITO KUALA",
    "HULU SUNGAI SELATAN",
    "HULU SUNGAI TENGAH",
    "HULU SUNGAI UTARA",
    "KOTABARU",
    "TABALONG",
    "TANAH BUMBU",
    "TANAH LAUT",
    "TAPIN",
    # Kalimantan Timur
    "BALIKPAPAN",
    "BONTANG",
    "SAMARINDA",
    "BERAU",
    "KUTAI BARAT",
    "KUTAI KARTANEGARA",
    "KUTAI TIMUR",
    "MAHAKAM ULU",
    "PASER",
    "PENAJAM PASER UTARA",
    # Kalimantan Utara
    "TARAKAN",
    "BULUNGAN",
    "MALINAU",
    "NUNUKAN",
    "TANA TIDUNG",
    # Sulawesi Utara
    "MANADO",
    "BITUNG",
    "KOTAMOBAGU",
    "TOMOHON",
    "BOLAANG MONGONDOW",
    "BOLAANG MONGONDOW SELATAN",
    "BOLAANG MONGONDOW TIMUR",
    "BOLAANG MONGONDOW UTARA",
    "KEPULAUAN SANGIHE",
    "KEPULAUAN SIAU TAGULANDANG BIARO",
    "KEPULAUAN TALAUD",
    "MINAHASA",
    "MINAHASA SELATAN",
    "MINAHASA TENGGARA",
    "MINAHASA UTARA",
    # Sulawesi Tengah
    "PALU",
    "BANGGAI",
    "BANGGAI KEPULAUAN",
    "BANGGAI LAUT",
    "BUOL",
    "DONGGALA",
    "MOROWALI",
    "MOROWALI UTARA",
    "PARIGI MOUTONG",
    "POSO",
    "SIGI",
    "TOJO UNA-UNA",
    "TOLI-TOLI",
    # Sulawesi Selatan
    "MAKASSAR",
    "PALOPO",
    "PAREPARE",
    "BANTAENG",
    "BARRU",
    "BONE",
    "BULUKUMBA",
    "ENREKANG",
    "GOWA",
    "JENEPONTO",
    "KEPULAUAN SELAYAR",
    "LUWU",
    "LUWU TIMUR",
    "LUWU UTARA",
    "MAROS",
    "PANGKAJENE DAN KEPULAUAN",
    "PINRANG",
    "SIDENRENG RAPPANG",
    "SINJAI",
    "SOPPENG",
    "TAKALAR",
    "TANA TORAJA",
    "TORAJA UTARA",
    "WAJO",
    # Sulawesi Tenggara
    "KENDARI",
    "BAU-BAU",
    "BOMBANA",
    "BUTON",
    "BUTON SELATAN",
    "BUTON TENGAH",
    "BUTON UTARA",
    "KOLAKA",
    "KOLAKA TIMUR",
    "KOLAKA UTARA",
    "KONAWE",
    "KONAWE KEPULAUAN",
    "KONAWE SELATAN",
    "KONAWE UTARA",
    "MUNA",
    "MUNA BARAT",
    "WAKATOBI",
    # Gorontalo
    "GORONTALO",
    "BOALEMO",
    "BONE BOLANGO",
    "GORONTALO UTARA",
    "POHUWATO",
    # Sulawesi Barat
    "MAMUJU",
    "MAJENE",
    "MAMASA",
    "MAMUJU TENGAH",
    "MAMUJU UTARA",
    "POLEWALI MANDAR",
    # Maluku
    "AMBON",
    "TUAL",
    "BURU",
    "BURU SELATAN",
    "KEPULAUAN ARU",
    "MALUKU BARAT DAYA",
    "MALUKU TENGAH",
    "MALUKU TENGGARA",
    "MALUKU TENGGARA BARAT",
    "SERAM BAGIAN BARAT",
    "SERAM BAGIAN TIMUR",
    # Maluku Utara
    "TERNATE",
    "TIDORE KEPULAUAN",
    "HALMAHERA BARAT",
    "HALMAHERA SELATAN",
    "HALMAHERA TENGAH",
    "HALMAHERA TIMUR",
    "HALMAHERA UTARA",
    "KEPULAUAN SULA",
    "PULAU MOROTAI",
    "PULAU TALIABU",
    # Papua
    "JAYAPURA",
    "ASMAT",
    "BIAK NUMFOR",
    "BOVEN DIGOEL",
    "DEIYAI",
    "DOGIYAI",
    "INTAN JAYA",
    "JAYAPURA",
    "JAYAWIJAYA",
    "KEEROM",
    "KEPULAUAN YAPEN",
    "LANNY JAYA",
    "MAMBERAMO RAYA",
    "MAMBERAMO TENGAH",
    "MAPPI",
    "MERAUKE",
    "MIMIKA",
    "NABIRE",
    "NDUGA",
    "PANIAI",
    "PEGUNUNGAN BINTANG",
    "PUNCAK",
    "PUNCAK JAYA",
    "SARMI",
    "SUPIORI",
    "TOLIKARA",
    "WAROPEN",
    "YAHUKIMO",
    "YALIMO",
    # Papua Barat
    "MANOKWARI",
    "SORONG",
    "FAK-FAK",
    "KAIMANA",
    "MANOKWARI SELATAN",
    "MAYBRAT",
    "PEGUNUNGAN ARFAK",
    "RAJA AMPAT",
    "SORONG",
    "SORONG SELATAN",
    "TAMBRAUW",
    "TELUK BINTUNI",
    "TELUK WONDAMA",
]

# Alias dan variasi nama yang sering muncul di OCR
PROVINSI_ALIASES = {
    "JAKARTA": "DKI JAKARTA",
    "DKI": "DKI JAKARTA",
    "YOGYAKARTA": "DI YOGYAKARTA",
    "DIY": "DI YOGYAKARTA",
    "YOGYA": "DI YOGYAKARTA",
    "BANGKA BELITUNG": "KEPULAUAN BANGKA BELITUNG",
    "KEP BANGKA BELITUNG": "KEPULAUAN BANGKA BELITUNG",
    "KEP RIAU": "KEPULAUAN RIAU",
    "SUMUT": "SUMATERA UTARA",
    "SUMBAR": "SUMATERA BARAT",
    "SUMSEL": "SUMATERA SELATAN",
    "JABAR": "JAWA BARAT",
    "JATENG": "JAWA TENGAH",
    "JATIM": "JAWA TIMUR",
    "KALBAR": "KALIMANTAN BARAT",
    "KALTENG": "KALIMANTAN TENGAH",
    "KALSEL": "KALIMANTAN SELATAN",
    "KALTIM": "KALIMANTAN TIMUR",
    "KALTARA": "KALIMANTAN UTARA",
    "SULUT": "SULAWESI UTARA",
    "SULTENG": "SULAWESI TENGAH",
    "SULSEL": "SULAWESI SELATAN",
    "SULTRA": "SULAWESI TENGGARA",
    "SULBAR": "SULAWESI BARAT",
    "NTB": "NUSA TENGGARA BARAT",
    "NTT": "NUSA TENGGARA TIMUR",
}
